.TH xsct 1 "Dec 2022" "1.9" "User Manual"
.SH NAME
xsct \- X11 set screen color temperature
.SH SYNOPSIS
.B xsct 
[options] 
.I [temperature]
.I [brightness]

.SH DESCRIPTION
.B xsct
sets the screen's color temperature.

.SH OPTIONS
.TP
.B -h, --help
Display usage information and exit
.TP
.B -v, --verbose
Display debugging information
.TP
.B -d, --delta
Shift temperature by temperature value
.TP
.B -s, --screen N
Zero-based index of screen to use.
.TP
.B -c, --crtc N
Zero-based index of CRTC to use.
.TP
.I [temperature]
Black body temperature
.br
If the value is 0, xsct sets the color temperature to the default of 6500
.br
If no arguments are passed, xsct estimates the current display temperature and brightness
.TP
.I [brightness]
Linear brightness between 0.0 (inclusive) and 1.0 (inclusive). The default value is 1.0 if no parameter is passed.

.SH AUTHOR
xsct is based on sct by Ted Unangst <tedu@openbsd.org>

.SH SEE ALSO
redshift(1), xtemp(1)
