.TH xsct 1 "Aug 2020" "1.6" "User Manual"
.SH NAME
xsct \- X11 set screen color temperature
.SH SYNOPSIS
.B xsct 
[options] 
.I [temperature]
.I [screen_index]
.I [crtc_index]

.SH DESCRIPTION
.B xsct
sets the screen's color temperature.

.SH OPTIONS
.TP
.B -d, --delta
Shift temperature by given value
.TP
.B -h, --help
Display usage information and exit
.TP
.B -v, --verbose
Display debugging information
.TP
.I [temperature]
Black body temperature
.br
If the value is 0, xsct sets the color temperature to the default of 6500
.br
If no arguments are passed, xsct estimates the current display temperature
.TP
.I [screen_index]
Screen to change temperature of.
.TP
.I [crtc_index]
CRTC (output) of specified screen to change temperature of.

.SH AUTHOR
xsct was written by Ted Unangst <tedu@openbsd.org>

.SH SEE ALSO
redshift(1), xtemp(1)
